version: '{build}'
skip_tags: true
image: Visual Studio 2019
platform:
  - x64
  - x86
clone_script:
  - cmd: git clone https://github.com/superjer/tinyc.games.git
environment:
  matrix:
  - job_name: blocko 
  - job_name: flappy
for:
  -
    matrix:
      only:
        - job_name: blocko
          configuration: 
            - Debug
          build:
            project: C:\projects\tinyc-games-ci\tinyc.games\blocko\vs2019-blocko\vs2019-blocko.sln
            verbosity: normal
          artifacts:
            - path: tinyc.games\blocko\vs2019-blocko\x64\Debug\vs2019-blocko.exe
            - name: debug-vs2019-blocko.exe
            - path: tinyc.games\blocko\vs2019-blocko\x64\Release\vs2019-blocko.exe
            - name: release-vs2019-blocko.exe
  -
    matrix:
      only:
        - job_name: flappy
    build_script:
    - cmd: dir
    
test: off
