version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Debug
platform:
- x64
- x86
environment:
  matrix:

  - job_name: blocko
    appveyor_build_project: C:\projects\tinyc-games-ci\tinyc.games\blocko\vs2019-blocko\vs2019-blocko.sln
    appveyor_build_verbosity: normal
    
  - job_name: flappy
    job_depends_on: Build
    
clone_script:
- cmd: git clone https://github.com/superjer/tinyc.games.git
test: off
artifacts:
  - path: tinyc.games\blocko\vs2019-blocko\x64\Debug\vs2019-blocko.exe
    name: vs2019-blocko.exe
