version: '{build}'
skip_tags: true
image: Visual Studio 2019

platform:
  - x64
  - x86
clone_script:
  - cmd: git clone https://github.com/superjer/tinyc.games.git
environment:
  matrix:
  - job_name: blocko 
  - job_name: flappy
for:

  -
    matrix:
      only:
        - job_name: blocko

    build:
      project: C:\projects\tinyc-games-ci\tinyc.games\blocko\vs2019-blocko\vs2019-blocko.sln
      verbosity: normal
  -
    matrix:
      only:
        - job_name: flappy

    build_script:
    - cmd: >-
    reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && (set ARCH=x86) || (set ARCH=x64)
    
    set CC=..\_win\tcc-%ARCH%\tcc.exe
    
    set SDL=..\_win\SDL2-2.0.5
    
    set TTF=..\_win\SDL2_ttf-2.0.14

    echo %CC%

    set PATH=%PATH%;%SDL%\lib\%ARCH%
    
    set PATH=%PATH%;%TTF%\lib\%ARCH%

    %CC% -DSDL_MAIN_HANDLED -I%SDL%\include -I%TTF%\include -L%SDL%\lib\%ARCH% -L%TTF%\lib\%ARCH% -lSDL2 -lSDL2_ttf flappy.c

#for:
#  - matrix:
#      only:
#        - job_name: blocko
#          
#        build:
#          - project: C:\projects\tinyc-games-ci\tinyc.games\blocko\vs2019-blocko\vs2019-blocko.sln
#          - verbosity: normal
#          
#        artifacts:
#         - path: tinyc.games\blocko\vs2019-blocko\x64\Debug\vs2019-blocko.exe
#          - name: debug-vs2019-blocko.exe
#          - path: tinyc.games\blocko\vs2019-blocko\x64\Release\vs2019-blocko.exe
#          - name: release-vs2019-blocko.exe
#  - matrix:
#      only:
#        - job_name: flappy
#        
#        build_script:
#          - cmd: dir
#    
test: off
