version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Debug
platform:
- x64
clone_script:
- cmd: git clone https://github.com/superjer/tinyc.games.git
build:
  project: C:\projects\tinyc-games-ci\tinyc.games\blocko\vs2019-blocko\vs2019-blocko.sln
  verbosity: normal
test: off
artifacts:
  - path: tinyc.games\blocko\vs2019-blocko\x64\Debug\vs2019-blocko.exe
    name: vs2019-blocko.exe
