version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Debug
platform:
- x64
- x86
clone_script:
- cmd: git clone https://github.com/superjer/tinyc.games.git
environment:
  matrix:
  - job_name: blocko 
  build:
    project: C:\projects\tinyc-games-ci\tinyc.games\blocko\vs2019-blocko\vs2019-blocko.sln
    verbosity: normal  
    artifacts:
      - path: tinyc.games\blocko\vs2019-blocko\x64\Debug\vs2019-blocko.exe
  - job_name: flappy
  build_script:
    - cmd: dir
test: off
