name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  linux:
    runs-on: windows-2016
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
    - name: get source
      run: |
        certutil -urlcache -split -f https://sourceforge.net/projects/glew/files/latest/download glew.tgz
        C:\"Program files"\7-Zip\7z.exe x glew.tgz -oglew
        mv glew\glew.tar .
        C:\"Program files"\7-Zip\7z.exe x glew.tar -oglew
        mv glew\* .
        mv glew-* glew-src
    - name: build
      working-directory: D:\a\tinyc.games-ci\tinyc.games-ci\glew-src\build\vc15
      run: |
        C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\Common7\IDE\devenv.com glew.sln /Build "Release|x64" /Project visualinfo 
        C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\Common7\IDE\devenv.com glew.sln /Build "Release|x64" /Project glew_shared /Project glewinfo
      # C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\Common7\IDE\devenv.com glew.sln /Build "Release|x64" /Project visualinfo
      # ls ..\..\
    - name: push
      run: |
        ls glew/
        git add .
        git commit -m "auto upgrade glew"
        git push origin dependence
