name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  linux:
    runs-on: windows-2016
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
        path: files
    - name: prepare build
      run: |
        git clone https://github.com/SDL-mirror/SDL.git sdl-src
        git clone https://github.com/SDL-mirror/SDL_ttf.git sdl-ttf-src
        git clone https://github.com/nigels-com/glew.git glew-src
        mkdir sdl
        mkdir sdl-ttf
        mkdir glew
    - name: sdl
      working-directory: sdl-src\VisualC
      run: |
        #cd VisualC
        dir C:\"Program Files (x86)"\"Microsoft Visual Studio 10.0"\Common7\IDE
        C:\"Program Files (x86)"\"Microsoft Visual Studio 10.0"\Common7\IDE\VC\Bin\vcvarsall.bat
        devenv SDL.sln /build "Release|Win64" /Project SDL
    #- name: sdl-ttf
   #   working-directory: sdl-ttf-src
   #   run: |
  #  - name: glew
    #  working-directory: glew-src/build
   #   run: |
    - name: push
      run: |
        ls glew/
        ls sdl/
        ls sdl-ttf/
        git add .
        git commit -m "auto upgrade dependence"
        git push origin dependence
