name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
        path: files
    - name: prepare build
      run: |
        git clone https://github.com/SDL-mirror/SDL.git sdl-src
        git clone https://github.com/SDL-mirror/SDL_ttf.git sdl-ttf-src
        git clone https://github.com/nigels-com/glew.git glew-src
        mkdir sdl
        mkdir sdl-ttf
        mkdir glew
    - name: sdl
      run: |
        ls
        cd sdl-src
        ./configure --prefix=../sdl
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l)
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l) install
    - name: sdl-ttf
      working-directory: sdl-ttf-src
      run: |
        ./configure --prefix=../sdl
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l)
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l) install
    - name: glew
      working-directory: glew-src/build
      run: |
        sudo apt-get install build-essential libxmu-dev libxi-dev libgl-dev cmake
        cmake ./cmake -DCMAKE_INSTALL_PREFIX=../../glew -DBUILD_UTILS=ON
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l) glew
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l) glewinfo
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l) visualinfo
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l) install
    - name: push
      run: |
        ls glew/
        ls sdl/
        ls sdl-ttf/
        git add .
        git commit -m "auto upgrade dependence"
        git push origin dependence
