name: dependence-win

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  glew:
    runs-on: windows-2016
    steps:
    
    - name: Get glew source
      run: |
        certutil -urlcache -split -f https://sourceforge.net/projects/glew/files/latest/download glew.tgz
        C:\"Program files"\7-Zip\7z.exe x glew.tgz -oglew
        mv glew\glew.tar .
        C:\"Program files"\7-Zip\7z.exe x glew.tar -oglew
        mv glew\* .
        mv glew-* glew-src
    - name: Build x64 arch
      shell: cmd
      working-directory: glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64
        devenv glew.sln /Build "Release|x64" /Project glew_shared
        devenv glew.sln /Build "Release|x64" /Project visualinfo
        devenv glew.sln /Build "Release|x64" /Project glewinfo
        ls ..\..\
    - name: Build x86 arch
      shell: cmd
      working-directory: glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86
        devenv glew.sln /Build "Release|Win32" /Project glew_shared
        devenv glew.sln /Build "Release|Win32" /Project visualinfo
        devenv glew.sln /Build "Release|Win32" /Project glewinfo
        ls ..\..\
    - name: Prepare files
      run: |
        cp -r glew-src\bin glew\
        cp -r glew-src\doc glew\
        cp -r glew-src\include glew\
        cp -r glew-src\lib glew\
        cp glew-src\LICENSE.txt glew\
    - name: Cache glew
      uses: actions/cache@main
      with:
        path: glew
        key: win-glew
    - name: Upload glew
      uses: actions/upload-artifact@v2
      with:
        name: glew
        path: glew
