name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  linux:
    runs-on: windows-2019
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
    - name: prepare build
      run: |
        git clone https://github.com/nigels-com/glew.git glew-src
        mkdir glew
    - name: build glew
      working-directory: D:\a\tinyc.games-ci\tinyc.games-ci\glew-src\build
      run: |
        cmake ./cmake -G "Visual Studio 16 2019"
        C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\Common7\IDE\devenv.com glew.sln /Build "Release|Win32" /Project glew
        ls
    - name: push
      run: |
        ls glew/
        git add .
        git commit -m "auto upgrade glew"
        git push origin dependence
