name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  glew:
    runs-on: windows-2016
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
    - name: get source
      run: |
        certutil -urlcache -split -f https://sourceforge.net/projects/glew/files/latest/download glew.tgz
        C:\"Program files"\7-Zip\7z.exe x glew.tgz -oglew
        mv glew\glew.tar .
        C:\"Program files"\7-Zip\7z.exe x glew.tar -oglew
        mv glew\* .
        mv glew-* glew-src
    - name: build x64
      working-directory: D:\a\tinyc.games-ci\tinyc.games-ci\glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64
        devenv.com glew.sln /Build "Release|x64" /Project glew_shared
        devenv.com glew.sln /Build "Release|x64" /Project visualinfo
        devenv.com glew.sln /Build "Release|x64" /Project glewinfo
        ls ..\..\
    - name: build x86
      working-directory: D:\a\tinyc.games-ci\tinyc.games-ci\glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86
        devenv.com glew.sln /Build "Release|Win32" /Project glew_shared
        devenv.com glew.sln /Build "Release|Win32" /Project visualinfo
        devenv.com glew.sln /Build "Release|Win32" /Project glewinfo
        ls ..\..\
    - name: push
      run: |
        ls glew/
        git add .
        git commit -m "auto upgrade glew"
        git push origin dependence
