name: dependence-mac

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  sdl:
    runs-on: macos-latest

    steps:
      - name: Get sdl source
        run: |
          git clone https://github.com/SDL-mirror/SDL.git
          cd SDL
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
      - name: Build
        working-directory: SDL/Xcode/SDL
        run: |
          sudo xcode-select -switch /Applications/Xcode_10.3.app
          xcodebuild -scheme Framework VALID_ARCHS="i386 x86_64" -configuration 'Release'
          cp -r /Users/runner/Library/Developer/Xcode/DerivedData/SDL-gserqlkghybkaxdggwarbuabfcuy/Build/Products/Release/SDL2.framework ../../../SDL2.framework
      - name: Cache
        uses: actions/cache@main
        with:
          key: sdl-mac-${{ github.run_id }}
          path: SDL2.framework
  sdl_ttf:
    needs: [sdl]
    runs-on: macos-latest
    steps:
      - name: Get sdl_ttf source
        run: |
          git clone https://github.com/SDL-mirror/SDL_ttf.git
          cd SDL_ttf
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
      - name: Get sdl cache
        uses: actions/cache@main
        with:
          key: sdl-mac-${{ github.run_id }}
          path: SDL2.framework
      - name: build
        working-directory: SDL_ttf/Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_10.3.app
          cp -r ../../SDL2.framework ./Frameworks/SDL2.framework
          sudo cp ./Frameworks/SDL2.framework/Headers/*	/Applications/Xcode_10.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
          xcodebuild -scheme Framework VALID_ARCHS="i386 x86_64" -configuration 'Release'
          cp -r /Users/runner/Library/Developer/Xcode/DerivedData/SDL_ttf-bkqeqlcqtitnvrbrxydginuzbljt/Build/Products/Release/SDL2_ttf.framework ../../SDL2_ttf.framework
      - name: Cache
        uses: actions/cache@main
        with:
          key: sdl-mac-${{ github.run_id }}
          path: SDL2.framework
  sdl_net:
    runs-on: macos-latest
    needs: [sdl]
    steps:
      - name: Get sdl_net source
        run: |
          git clone https://github.com/SDL-mirror/SDL_net.git
          cd SDL_net
        #  git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
      - name: Get sdl cache
        uses: actions/cache@main
        with:
          key: sdl-mac-${{ github.run_id }}
          path: SDL2.framework
      - name: build
        working-directory: SDL_net/Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_10.3.app
          sudo cp ../../SDL2.framework/Headers/*	/Applications/Xcode_10.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
          xcodebuild -scheme Framework VALID_ARCHS="i386 x86_64" -configuration 'Release'
