name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  linux:
    runs-on: windows-2019
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
    - name: prepare build
      run: |
        choco install 7zip.install
        certutil.exe -urlcache -split -f https://sourceforge.net/projects/glew/files/latest/download glew.tgz
        7za x glew.tgz -o glew-src
      # git clone https://github.com/nigels-com/glew.git glew-src
        mkdir glew
    - name: gen sln
      working-directory: D:\a\tinyc.games-ci\tinyc.games-ci\glew-src\build\vc16
      run: |
        cmake ../cmake -G "Visual Studio 16 2019"
    - name: build dll
      working-directory: D:\a\tinyc.games-ci\tinyc.games-ci\glew-src\build\vc16
      run: |
        C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\Common7\IDE\devenv.com glew.sln /Build "Release|Win32" /Project glew
        ls
    - name: push
      run: |
        ls glew/
        git add .
        git commit -m "auto upgrade glew"
        git push origin dependence
