name: dependence-win

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  glew:
    runs-on: windows-2016
    steps:  
    - name: Get glew source
      run: |
        certutil -urlcache -split -f https://sourceforge.net/projects/glew/files/latest/download glew.tgz
        C:\"Program files"\7-Zip\7z.exe x glew.tgz -oglew
        mv glew\glew.tar .
        C:\"Program files"\7-Zip\7z.exe x glew.tar -oglew
        mv glew\* .
        mv glew-* glew-src
    - name: Build x64 arch
      shell: cmd
      working-directory: glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64
        msbuild /m glew.sln /p:Configuration=Release;Platform=x64
        ls ..\..\
    - name: Build x86 arch
      shell: cmd
      working-directory: glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86
        msbuild /m glew.sln /p:Configuration=Release;Platform=Win32
        ls ..\..\
    - name: Prepare files
      run: |
        cp -r glew-src\bin glew\
        cp -r glew-src\doc glew\
        cp -r glew-src\include glew\
        cp -r glew-src\lib glew\
        cp glew-src\LICENSE.txt glew\
    - name: Cache glew
      uses: actions/cache@main
      with:
        key: glew-win-${{ github.run_id }}
        path: glew
    - name: Upload glew
      uses: actions/upload-artifact@v2
      with:
        name: glew-${{ github.run_id }}
        path: glew
  sdl:
    runs-on: windows-2019
    steps:
      - name: Get sdl source & prepare build
        run: |
          git clone https://github.com/SDL-mirror/SDL.git
          cd SDL
          git checkout (git describe --tags (git rev-list --tags --max-count=1))
          cd ..
          mkdir sdl2 | Out-Null
          mkdir sdl2\lib | Out-Null
          mkdir sdl2\lib\x64 | Out-Null
          mkdir sdl2\lib\x86 | Out-Null
      - name: Build x64 arch
        working-directory: SDL\VisualC\SDL
        shell: cmd 
        run: |
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64 > NUL
          msbuild SDL.vcxproj /m /nologo /p:Configuration=Release;Platform=x64;PlatformToolset=v142
          cd ..\SDLmain
          msbuild SDLmain.vcxproj /m /nologo /p:Configuration=Release;Platform=x64;PlatformToolset=v142
          cd ..\SDLtest
          msbuild SDLtest.vcxproj /m /nologo /p:Configuration=Release;Platform=x64;PlatformToolset=v142
      - name: Build x86 arch
        working-directory: SDL\VisualC\SDL
        shell: cmd 
        run: |
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86 > NUL
          msbuild SDL.vcxproj /m /nologo /p:Configuration=Release;Platform=Win32;PlatformToolset=v142
          cd ..\SDLmain
          msbuild SDLmain.vcxproj /m /nologo /p:Configuration=Release;Platform=Win32;PlatformToolset=v142
          cd ..\SDLtest
          msbuild SDLtest.vcxproj /m /nologo /p:Configuration=Release;Platform=Win32;PlatformToolset=v142
      - name: Prepare files
        working-directory: sdl2\lib
        run: |
          cp ..\..\SDL\VisualC\SDL\x64\Release\SDL2.dll .\x64\
          cp ..\..\SDL\VisualC\SDL\x64\Release\SDL2.lib .\x64\
          cp ..\..\SDL\VisualC\SDLmain\x64\Release\SDL2main.lib .\x64\
          cp ..\..\SDL\VisualC\SDLtest\x64\Release\SDL2test.lib .\x64\
          cp ..\..\SDL\VisualC\SDL\Win32\Release\SDL2.dll .\x86\
          cp ..\..\SDL\VisualC\SDL\Win32\Release\SDL2.lib .\x86\
          cp ..\..\SDL\VisualC\SDLmain\Win32\Release\SDL2main.lib .\x86\
          cp ..\..\SDL\VisualC\SDLtest\Win32\Release\SDL2test.lib .\x86\
          cd ..
          cp -r ..\SDL\docs .\
          cp -r ..\SDL\include .\
          cp ..\SDL\BUGS.txt .\
          cp ..\SDL\COPYING.txt .\
          cp ..\SDL\README-SDL.txt .\
          cp ..\SDL\README.txt .\
          cp ..\SDL\WhatsNew.txt .\
      - name: Cache sdl
        uses: actions/cache@main
        with:
          key: sdl-win-${{ github.run_id }}
          path: sdl2
      - uses: actions/upload-artifact@v2
        with:
          name: sdl-win-${{ github.run_id }}
          path: sdl2
  sdl_ttf:
    needs: sdl
    runs-on: windows-2019  
    steps:
      - name: Restore sdl
        uses: actions/cache@main
        with:
          key: sdl-win-${{ github.run_id }}
          path: sdl2
      - name: Get sdl_ttf source & prepare build
        run: |
          ls sdl2\
          git clone https://github.com/SDL-mirror/SDL_ttf.git
          cd SDL_ttf
          git checkout (git describe --tags (git rev-list --tags --max-count=1))
          mkdir sdl_ttf | Out-Null
          mkdir sdl_ttf\include | Out-Null
          mkdir sdl_ttf\lib | Out-Null
          copy sdl2\include\*.h VisualC\external\include\
          copy sdl2\lib\x86\SDL2.lib VisualC\external\lib\x86\
          copy sdl2\lib\x64\SDL2.lib VisualC\external\lib\x64\
      - name: Build x64 arch
        shell: cmd
        working-directory: SDL_ttf\VisualC
        run: |
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64 > NUL
          msbuild SDL_ttf.vcxproj /m /nologo /p:Configuration=Release;Platform=x64;PlatformToolset=v142
      - name: Build x86 arch
        shell: cmd
        working-directory: SDL_ttf\VisualC
        run: |
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86 > NUL
          msbuild SDL_ttf.vcxproj /m /nologo /p:Configuration=Release;Platform=Win3;PlatformToolset=v142
      - name: Prepare files
        working-directory: SDL_ttf\sdl_ttf
        run: |
          ls ..\VisualC
  tinycc:
    runs-on: windows-2019
    steps:
      - name: Get sdl source
        run: git clone -b mob git://repo.or.cz/tinycc.git
      - name: Build all arch
        shell: cmd
        working-directory: tinycc\win32
        run: |
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64
          call build-tcc.bat -c cl -t 64 -i tcc-x64
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86
          call build-tcc.bat -c cl -t 32 -i tcc-x86
      - name: Cache x64 tinycc
        uses: actions/cache@main
        with:
          key: tcc-x64-win-${{ github.run_id }}
          path: tinycc\win32\tcc-x64
      - name: Cache x86 tinycc
        uses: actions/cache@main
        with:
          key: tcc-x86-win-${{ github.run_id }}
          path: tinycc\win32\tcc-x86
      - name: Upload x64 tinycc
        uses: actions/upload-artifact@v2
        with:
          name: tcc-x64-${{ github.run_id }}
          path: tinycc\win32\tcc-x64
      - name: Upload x86 tinycc
        uses: actions/upload-artifact@v2
        with:
          name: tcc-x86-${{ github.run_id }}
          path: tinycc\win32\tcc-x86
