name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
        path: files
    - uses: actions/checkout@main
      with:
        repository: SDL-mirror/SDL
        path: sdl
    - name: sdl
      working-directory: sdl
      run: |
        mkdir ../files/sdl
        ./configure --prefix=../files/sdl
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l)
        make -j$(cat /proc/cpuinfo |grep "processor"|sort -u|wc -l) install
        ls ../files/sdl/
