name: dependence

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  linux:
    runs-on: windows-2019
    steps:
    
    - uses: actions/checkout@main
      with:
        ref: dependence
        path: files
    - name: prepare build
      run: |
        git clone https://github.com/SDL-mirror/SDL.git sdl-src
        git clone https://github.com/SDL-mirror/SDL_ttf.git sdl-ttf-src
        git clone https://github.com/nigels-com/glew.git glew-src
        mkdir sdl
        mkdir sdl-ttf
        mkdir glew
    - name: glew
    #  working-directory: glew-src/build/vc14
      run: |
        dir
        C:\msys64\usr\bin\bash.exe
        pacman -S gcc make mingw-w64-i686-gcc mingw-w64-x86_64-gcc
        make
        make install
        make install.all
       # #C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\Common7\IDE\devenv.com glew.sln /build "Release|Win64" /Project glewinfo
     #   C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe glew.sln -property:Configuration=Debug
   #- name: sdl-ttf
   #   working-directory: sdl-ttf-src
   #   run: |
  #  - name: glew
    #  working-directory: glew-src/build
   #   run: |
    - name: push
      run: |
        ls glew/
        ls sdl/
        ls sdl-ttf/
        git add .
        git commit -m "auto upgrade dependence"
        git push origin dependence
