name: dependence-win

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  glew:
    runs-on: windows-2016
    steps:  
    - name: Get glew source
      run: |
        certutil -urlcache -split -f https://sourceforge.net/projects/glew/files/latest/download glew.tgz
        C:\"Program files"\7-Zip\7z.exe x glew.tgz -oglew
        mv glew\glew.tar .
        C:\"Program files"\7-Zip\7z.exe x glew.tar -oglew
        mv glew\* .
        mv glew-* glew-src
    - name: Build x64 arch
      shell: cmd
      working-directory: glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64
        msbuild /m glew.sln /p:Configuration=Release;Platform=x64
        ls ..\..\
    - name: Build x86 arch
      shell: cmd
      working-directory: glew-src\build\vc15
      run: |
        call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86
        msbuild /m glew.sln /p:Configuration=Release;Platform=Win32
        ls ..\..\
    - name: Prepare files
      run: |
        cp -r glew-src\bin glew\
        cp -r glew-src\doc glew\
        cp -r glew-src\include glew\
        cp -r glew-src\lib glew\
        cp glew-src\LICENSE.txt glew\
    - name: Cache glew
      uses: actions/cache@main
      with:
        key: glew-${{ runner.os }}
        path: glew
    - name: Upload glew
      uses: actions/upload-artifact@v2
      with:
        name: glew
        path: glew
  sdl:
    runs-on: windows-2019
    steps:
      - name: Get sdl source & prepare build
        run: |
          git clone https://github.com/SDL-mirror/SDL.git
          cd SDL
          git checkout (git describe --tags (git rev-list --tags --max-count=1))
          mkdir sdl | Out-Null
          mkdir sdl\lib | Out-Null
          mkdir sdl\lib\x64 | Out-Null
          mkdir sdl\lib\x86 | Out-Null
      - name: Build x64 arch
        working-directory: SDL\VisualC\SDL
        shell: cmd 
        run: |
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64 > NUL
          msbuild SDL.vcxproj /m /nologo /p:Configuration=Release;Platform=x64;PlatformToolset=v142
          cd ..\SDLmain
          msbuild SDLmain.vcxproj /m /nologo /p:Configuration=Release;Platform=x64;PlatformToolset=v142
          cd ..\SDLtest
          msbuild SDLtest.vcxproj /m /nologo /p:Configuration=Release;Platform=x64;PlatformToolset=v142
      - name: Build x86 arch
        working-directory: SDL\VisualC\SDL
        shell: cmd 
        run: |
          call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64_x86 > NUL
          msbuild SDL.vcxproj /m /nologo /p:Configuration=Release;Platform=Win32;PlatformToolset=v142
          cd ..\SDLmain
          msbuild SDLmain.vcxproj /m /nologo /p:Configuration=Release;Platform=Win32;PlatformToolset=v142
          cd ..\SDLtest
          msbuild SDLtest.vcxproj /m /nologo /p:Configuration=Release;Platform=Win32;PlatformToolset=v142
      - name: Prepare files
        working-directory: SDL\sdl\lib
        run: |
          cp ..\VisualC\SDL\x64\Release\SDL2.dll .\x64\
          cp ..\VisualC\SDL\x64\Release\SDL2.lib .\x64\
          cp ..\VisualC\SDLmain\x64\Release\SDL2main.lib .\x64\
          cp ..\VisualC\SDLtest\x64\Release\SDL2test.lib .\x64\
          cp ..\VisualC\SDL\Win32\Release\SDL2.dll .\x86\
          cp ..\VisualC\SDL\Win32\Release\SDL2.lib .\x86\
          cp ..\VisualC\SDLmain\Win32\Release\SDL2main.lib .\x86\
          cp ..\VisualC\SDLtest\Win32\Release\SDL2test.lib .\x86\
          cd ..
          cp -r ..\docs .\
          cp -r ..\include .\
          cp ..\BUGS.txt .\
          cp ..\COPYING.txt .\
          cp ..\README-SDL.txt .\
          cp ..\README.txt .\
          cp ..\WhatsNew.txt .\
          ls .
          ls lib\
      - uses: actions/upload-artifact@v2
        with:
          name: sdl
          path: SDL\sdl
