name: flappy

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: superjer/tinyc.games
    - name: install software
      run: sudo apt install tcc libsdl2-dev libsdl2-ttf-dev libglew-dev libpulse0
    - name: build flappy
      run: |
        cd flappy
        tcc -I /usr/include/SDL2 -I /usr/lib/x86_64-linux-gnu -I /usr/lib/x86_64-linux-gnu/pulseaudio -lSDL2 -lSDL2_ttf -o flappy.c
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: flappy
        path: flappy\flappy
