name: CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: superjer/tinyc.games
    - name: install software
      run: sudo apt install tcc libsdl2-dev libsdl2-ttf-dev libglew-dev libpulse0
    - name: build flappy
      run: |
        #ln /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so /usr/lib/x86_64-linux-gnu/libpulsecommon-11.1.so
        cd flappy
        tcc -lSDL2 -lSDL2_ttf flappy.c #-I/usr/include/SDL2 -lSDL2 -lSDL2_ttf flappy.c
