name: .NET Core

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
      with:
        repository: superjer/tinyc.games
    - name: setup dotnet
      run: |
        C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "new-object System.Net.WebClient.DownloadFile('https://github.com/actions/setup-dotnet/raw/main/externals/install-dotnet.ps1', 'D:/install-dotnet.ps1')"
        C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\install-dotnet.ps1' -Version 4.5"
   #- uses: actions/setup-dotnet@main
      #with:
        #dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd blocko\vs2019-blocko
        #dotnet restore
        #npm install --global --production windows-build-tools
    - name: Build
      run: |
        cd blocko\vs2019-blocko
        dotnet build --configuration Release --no-restore --nologo
        #MSBuild vs2019-blocko.sln -property:Conf
        dir
    - name: Test
      run: dotnet test --no-restore --verbosity normal
