name: Windows test
on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]
jobs:
  blocko:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
      with:
        repository: superjer/tinyc.games
    - name: Build blocko
      working-directory: blocko\vs2019-blocko
      run: |
        #C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe vs2019-blocko.sln -property:Configuration=Release -property:Platform=x64 -property:WarningLevel=0
    - uses: actions/upload-artifact@main
      with:
        name: vs2019-blocko.exe
        path: blocko\vs2019-blocko\x64\release\vs2019-blocko.exe
  flappy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: superjer/tinyc.games
      - name: Build flappy
        working-directory: flappy
        run: |
          ..\_win\tcc-x64\tcc.exe -DSDL_MAIN_HANDLED -I..\_win\SDL2-2.0.5\include -I..\_win\SDL2_ttf-2.0.14\include -L..\_win\SDL2-2.0.5\lib\x64 -L..\_win\SDL2_ttf-2.0.14\lib\x64 -lSDL2 -lSDL2_ttf flappy.c
          dir
