name: .NET Core

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
      with:
        repository: superjer/tinyc.games
    #- uses: actions/setup-dotnet@main
    #  with:
    #    dotnet-version: 5.0.x
    - uses: microsoft/setup-msbuild@master
    - name: Build blocko
      run: |
        cd blocko\vs2019-blocko
        MSBuild vs2019-blocko.sln -property:Configuration=Release -property:Platform=x64 -property:WarningLevel=0
        MSBuild vs2019-blocko.sln -property:Configuration=Release -property:Platform=x86 -property:WarningLevel=0
        dir x64\release
        dir x86\release
