name: Windows test
on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]
jobs:
  blocko:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
      with:
        repository: superjer/tinyc.games
    - name: Build blocko
      run: |
        C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64
        devenv
        MSBuild blocko\vs2019-blocko\vs2019-blocko.sln -property:Configuration=Release -property:Platform=x64 -property:WarningLevel=0
      #  mkdir blocko
     #   copy vs2019-blocko\x64\release\vs2019-blocko.exe blocko\
   #     copy _win\SDL2-2.0.5\lib\x64\SDL2.dll blocko\
    #    copy _win\glew-2.1.0\bin\Release\x64\glew32.dll blocko\
    - uses: actions/upload-artifact@main
      with:
        name: blocko-x64.exe
        path: blocko\vs2019-blocko\x64\release\vs2019-blocko.exe
  flappyandtet:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: superjer/tinyc.games
      - name: Build flappy & tet
        run: |
          cd flappy
          ..\_win\tcc-x64\tcc.exe -DSDL_MAIN_HANDLED -I..\_win\SDL2-2.0.5\include -I..\_win\SDL2_ttf-2.0.14\include -L..\_win\SDL2-2.0.5\lib\x64 -L..\_win\SDL2_ttf-2.0.14\lib\x64 -lSDL2 -lSDL2_ttf flappy.c
          cd ../tet
          ..\_win\tcc-x64\tcc.exe -DSDL_MAIN_HANDLED -I..\_win\SDL2-2.0.5\include -I..\_win\SDL2_ttf-2.0.14\include -L..\_win\SDL2-2.0.5\lib\x64 -L..\_win\SDL2_ttf-2.0.14\lib\x64 -lSDL2 -lSDL2_ttf tet.c
      - name: Upload flappy
        uses: actions/upload-artifact@main
        with:
          name: flappy.exe
          path: flappy\flappy.exe
      - name: Upload tet
        uses: actions/upload-artifact@main
        with:
          name: tet.exe
          path: tet\tet.exe
  #tet:
  #  runs-on: windows-latest
  #  steps:
   #   - uses: actions/checkout@main
   #     with:
    #      repository: superjer/tinyc.games
    #  - name: Build tet
     #   working-directory: tet
      #  run: |
      #    ..\_win\tcc-x64\tcc.exe -DSDL_MAIN_HANDLED -I..\_win\SDL2-2.0.5\include -I..\_win\SDL2_ttf-2.0.14\include -L..\_win\SDL2-2.0.5\lib\x64 -L..\_win\SDL2_ttf-2.0.14\lib\x64 -lSDL2 -lSDL2_ttf tet.c
