name: .NET Core

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
      with:
        repository: superjer/tinyc.games
    - uses: actions/setup-dotnet@main
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd blocko\vs2019-blocko
        #dotnet restore
        #npm install --global --production windows-build-tools
    - name: Build
      run: |
        cd blocko\vs2019-blocko
        dotnet build --configuration Release --platform x64 --no-restore --nologo
        #MSBuild vs2019-blocko.sln -property:Configuration=Release -property:Platform=x64
        dir
    - name: Test
      run: dotnet test --no-restore --verbosity normal
